# Generated by Django 5.0.1 on 2024-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientappointmentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('phone_no', models.CharField(max_length=12)),
                ('hsptlname', models.CharField(max_length=35)),
                ('date', models.DateField()),
                ('timings', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='patientloginmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='patientregistermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=6)),
                ('blood_grp', models.CharField(max_length=5)),
                ('heigth', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('material_status', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('username', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='hospitalModel',
        ),
    ]
